nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']  # Spécifiez ici votre domaine frontend exact
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 3600
        allow_credentials: true  # Permet les credentials (cookies, auth headers)
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']  # Spécifiez ici votre domaine frontend exact
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600
            allow_credentials: true  # Permet les credentials (cookies, auth headers)
